Project1/Controllers/DisplayDataController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using System.Dynamic;
using Project1.Models;

namespace Project1.Controllers
{
    public class DisplayDataController : Controller
    {
        public ActionResult Index()
        {
            dynamic model = new ExpandoObject();
            model.GenericInfo = GetGenericInfo();
            model.Schooling = GetSchooling();
            model.Intermediate = GetIntermediate();
            model.Graduation = GetGraduation();
            model.Family = GetFamily();
            return View(model);
        }

        private static List<GenericInfo> GetGenericInfo()
        {
            List<GenericInfo> CUSTOMER = new List<GenericInfo>();
            var dbconfig = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json").Build();
            string dbconnectionstr = dbconfig["ConnectionStrings:DefaultConnection"];
            using (SqlConnection con = new SqlConnection(dbconnectionstr))
            {
                SqlCommand cmd = new SqlCommand("SP_DISPLAY_TBL_GenericInfo", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                con.Open();
                using (SqlDataReader sdr = cmd.ExecuteReader())
                {
                    while (sdr.Read())
                    {
                        CUSTOMER.Add(new GenericInfo
                        {
                            HTDID = Convert.ToInt32(sdr["HTDID"].ToString()),
                            Sno = Convert.ToInt32(sdr["Sno"].ToString()),
                            HallTicket = sdr["HallTicket"].ToString(),
                            Name = sdr["Name"].ToString(),
                            EmailID = sdr["EmailID"].ToString(),
                            Dob = Convert.ToDateTime(sdr["Dob"].ToString()),
                            Gender = sdr["Gender"].ToString(),
                            StudentPHno =sdr["StudentPHno"].ToString(),
                            StudentAadhar = sdr["StudentAadhar"].ToString(),
                        });
                    }
                }
                con.Close();
                return CUSTOMER;
            }
        }
        private static List<Schooling> GetSchooling()
        {
            List<Schooling> Schooling = new List<Schooling>();
            var dbconfig = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json").Build();
            string dbconnectionstr = dbconfig["ConnectionStrings:DefaultConnection"];
            using (SqlConnection con = new SqlConnection(dbconnectionstr))
            {
                SqlCommand cmd = new SqlCommand("SP_DISPLAY_TBL_Schooling", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                con.Open();
                using (SqlDataReader adr = cmd.ExecuteReader())
                {
                    while (adr.Read())
                    {
                        Schooling.Add(new Schooling
                        {
                            HTDID = Convert.ToInt32(adr["HTDID"].ToString()),
                            SchoolName = adr["SchoolName"].ToString(),
                            SscPassYear =Convert.ToDateTime(adr["SscPassYear"].ToString()),
                            SscAggregate = Convert.ToInt32(adr["SscAggregate"].ToString()),

                        });
                    }
                    con.Close();
                    return Schooling;
                }

            }
        }
        private static List<Intermediate> GetIntermediate()
        {
            List<Intermediate> Obj2 = new List<Intermediate>();
            var dbconfig = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json").Build();
            string dbconnectionstr = dbconfig["ConnectionStrings:DefaultConnection"];
            using (SqlConnection con = new SqlConnection(dbconnectionstr))
            {
                SqlCommand cmd = new SqlCommand("SP_DISPLAY_TBL_Intermediate", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                con.Open();
                using (SqlDataReader bdr = cmd.ExecuteReader())
                {
                    while (bdr.Read())
                    {
                        Obj2.Add(new Intermediate
                        {

                            HTDID = Convert.ToInt32(bdr["HTDID"].ToString()),
                            CollegeName = bdr["CollegeName"].ToString(),
                            IntermediatePassYear = Convert.ToDateTime(bdr["IntermediatePassYear"].ToString()),
                            IntermediateAggregate =Convert.ToInt32( bdr["IntermediateAggregate"].ToString()),
                        });
                    }
                    con.Close();
                    return Obj2;
                }

            }
        }
        private static List<Graduation> GetGraduation()
        {
            List<Graduation> Obj3 = new List<Graduation>();
            var dbconfig = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json").Build();
            string dbconnectionstr = dbconfig["ConnectionStrings:DefaultConnection"];
            using (SqlConnection con = new SqlConnection(dbconnectionstr))
            {
                SqlCommand cmd = new SqlCommand("SP_DISPLAY_Graduation", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                con.Open();
                using (SqlDataReader cdr = cmd.ExecuteReader())
                {
                    while (cdr.Read())
                    {
                        Obj3.Add(new Graduation
                        {

                            HTDID = Convert.ToInt32(cdr["HTDID"].ToString()),
                            EngineeringCollegeName = cdr["EngineeringCollegeName"].ToString(),
                            Branch = cdr["Branch"].ToString(),
                            EngineeringPassout = Convert.ToDateTime(cdr["EngineeringPassout"].ToString()),
                            Backlog = Convert.ToInt32(cdr["Backlog"].ToString()),
                            GraduationAggregate = Convert.ToInt32(cdr["Backlog"].ToString())
                        });
                    }
                    con.Close();
                    return Obj3;
                }

            }
        }
        private static List<Family> GetFamily()
        {
            List<Family> obj4 = new List<Family>();
            var dbconfig = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json").Build();
            string dbconnectionstr = dbconfig["ConnectionStrings:DefaultConnection"];
            using (SqlConnection con = new SqlConnection(dbconnectionstr))
            {
                SqlCommand cmd = new SqlCommand("SP_DISPLAY_Family", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                con.Open();
                using (SqlDataReader ddr = cmd.ExecuteReader())
                {
                    while (ddr.Read())
                    {
                        obj4.Add(new Family
                        {

                            HTDID = Convert.ToInt32(ddr["HTDID"].ToString()),
                            FathersName = ddr["FathersName"].ToString(),
                            PermanentAddress = ddr["PermanentAddress"].ToString(),
                            FathersMobileNo = ddr["FathersMobileNo"].ToString(),
                            MothersName = ddr["MothersName"].ToString(),

                            MothersOccupation = ddr["MothersName"].ToString(),

                        });
                    }
                    con.Close();
                    return obj4;
                }

            }
        }
    }
}

Project1/Controllers/LEVEL1Controller.cs
using Microsoft.AspNetCore.Mvc;
using Project1.BusinessLogic_bl;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Project1.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using System.Configuration;

using System.Data.SqlClient;
using System.Reflection;

namespace Project1.Controllers
{

    public class LEVEL1Controller : Controller
    {
        [HttpGet]
        public IActionResult Backlog()
        {
            return View(level.GetData());
        }
        [HttpGet]
        public IActionResult Condition()
        {
            return View(student.checking());
        }
        [HttpGet]
        public IActionResult Totaldata()
        {
            return View(student.GetData1());
        }
    }
}

Project1/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Project1.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using System.Configuration;
using Project1.BusinessLogic_bl;
using System.Data.SqlClient;
using System.Reflection;


namespace Project1.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult LOGIN()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LOGIN(AdminLogin OBJ)
        {
            if (ModelState.IsValid)
            {
                DataTable dt = new DataTable();
                dt = MainLogic.login(OBJ);

                if (dt.Rows.Count > 0)
                {

                    return RedirectToAction("Index");
                }

                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View();
            }
        }
        [HttpGet]

        public IActionResult REGISTER()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult REGISTER(MainModel OBJ)
        {
            ViewBag.Message = "formsubmitted";
            if (ModelState.IsValid)
            {
                bool res = MainLogic.Insertdata(OBJ);

                if (res == true)
                {

                    return View("LOGIN");
                }
                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View(OBJ);
            }
        }
       
        public IActionResult ADMINUSER()
        {
            return View();
        }
        
        [HttpGet]

        public IActionResult STUDENTADD()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult STUDENTADD(GenericInfo OBJ)
        {
            ViewBag.Message = "formsubmitted";
            if (ModelState.IsValid)
            {
                bool res = StudentADD.Insertdata(OBJ);

                if (res == true)
                {

                    return RedirectToAction("SSCDetails");
                }
                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View(OBJ);
            }
        }


        
        [HttpGet]

        public IActionResult SSCDetails()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SSCDetails(Schooling OBJ)
        {
            ViewBag.Message = "formsubmitted";
            if (ModelState.IsValid)
            {
                bool res = StudentADD.InsertSsc(OBJ);

                if (res == true)
                {

                    return RedirectToAction("Intermediate");
                }
                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View(OBJ);
            }
        }
        [HttpGet]

        public IActionResult Intermediate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Intermediate(Intermediate OBJ)
        {
            ViewBag.Message = "formsubmitted";
            if (ModelState.IsValid)
            {
                bool res = StudentADD.InsertIntermediate(OBJ);

                if (res == true)
                {

                    return RedirectToAction("Graduation");
                }
                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View(OBJ);
            }
        }

        [HttpGet]

        public IActionResult Graduation()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Graduation(Graduation OBJ)
        {
            ViewBag.Message = "formsubmitted";
            if (ModelState.IsValid)
            {
                bool res = StudentADD.InsertGraduation(OBJ);

                if (res == true)
                {

                    return RedirectToAction("Family");
                }
                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View(OBJ);
            }
        }
        [HttpGet]
        public IActionResult Family()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Family(Family OBJ)
        {
            ViewBag.Message = "formsubmitted";
            if (ModelState.IsValid)
            {
                bool res = StudentADD.InsertFamily(OBJ);

                if (res == true)
                {

                    return RedirectToAction("Upload","File");
                }
                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View(OBJ);
            }
        }
        
        public IActionResult condition()
        {
            
            return View();
        }
    }
}

Project1/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>

                    <li><a href="#">@Html.ActionLink("Registration","REGISTER","Project")</a></li>
                    <li><a href="#">@Html.ActionLink("LEVEL-1","Backlog","LEVEL1")</a></li>
                    <li><a href="#">@Html.ActionLink("LEVEL-2","LEVEL2","Project")</a></li>
                    <li><a href="#">@Html.ActionLink("LEVEL-3","LEVEL3","Project")</a></li>
                    <li><a href="#">@Html.ActionLink("ADMIN","ADMINUSER","Project")</a></li>


                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p> </p>
    </footer>
</body>
</html>

Project1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Project1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project1/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">@Html.ActionLink("ADMIN","ADMINUSER","Project")</a></li>
                  @*  <li><a href="#">@Html.ActionLink("Registration","REGISTER","Project")</a></li>*@
                    <li><a href="#">@Html.ActionLink("DisplaySTUDENTDATA","Index","DisplayData")</a></li>
                     <li><a href="#">@Html.ActionLink("STUDENTDATA","Totaldata","LEVEL1")</a></li>
                    <li><a href="#">@Html.ActionLink("LEVEL-1","Condition","LEVEL1")</a></li>
                    <li><a href="#">@Html.ActionLink("LEVEL-2","LEVEL2","Project")</a></li>
                    <li><a href="#">@Html.ActionLink("LEVEL-3","LEVEL3","Project")</a></li>
                   
                   

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="jumbotron">
        <div class="container text-center">
            <h1>Project1</h1>
            <p>Some text that represents "Me"...</p>
        </div>
    </div>

    <div class="container-fluid bg-3 text-center">
        <h3>Some of my Work</h3><br>
        <div class="row">
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
        </div>
    </div>
    <br>

    <div class="container-fluid bg-3 text-center">
        <div class="row">
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
        </div>
    </div>
    <br>
    <br>

    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>

</body>
</html>